### ISSUE TITLE
Fix Link In Table

### ISSUE THREAD

**Issue by pardus79** [nvk/bitcointreasuries.org#15]
![image](https://user-images.githubusercontent.com/9451785/95623992-02b1a480-0a2b-11eb-9b54-892e97ee1c84.png)

Points to http://bitcointresuries.com/

**Comment by nvk** [comment]
fixed

**Comment by pardus79** [comment]
Tested. Still getting directed to http://bitcointresuries.com/

Think this link is in the google doc.
